kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fsx-sc
provisioner: fsx.csi.aws.com
parameters:
  subnetId: subnet-0b7feca8e1a89866e
  securityGroupIds: sg-0068354d692c6b51d
  s3ImportPath: s3://fsx-antje
  s3ExportPath: s3://fsx-antje
  autoImportPolicy: NEW_CHANGED
  deploymentType: SCRATCH_2
mountOptions:
  - flock